"""Canonical schema baseline — full schema as a single Alembic revision.

The entire current schema is expressed here as ``op.create_table`` calls,
autogenerated from ``Base.metadata`` against an empty DB and hand-reviewed.
The partitioned ``coding_agent_activity`` parent is a raw ``op.execute`` because
Alembic autogenerate does not understand ``PARTITION BY RANGE``
(sqlalchemy/alembic #539, #1787).

Downgrade is not supported — this baseline is one-way.  Child partitions for
``coding_agent_activity`` are seeded by ``maintain_coding_agent_activity_partitions()``
called from ``core/database.migrate()`` after ``alembic upgrade head`` returns.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the canonical schema from scratch."""
    # Tables with no FK dependencies first.
    op.create_table(
        "agent_commands",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("workflow_execution_id", sa.UUID(), nullable=True),
        sa.Column("command_kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("completion_token_hash", sa.String(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_commands_agent_status_id", "agent_commands", ["agent_id", "status", "id"], unique=False
    )
    op.create_index(
        "ix_agent_commands_status_kind_id", "agent_commands", ["status", "command_kind", "id"], unique=False
    )

    op.create_table(
        "audit_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("entity_kind", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_kind", sa.String(), nullable=False),
        sa.Column("actor_login", sa.String(), nullable=True),
        sa.Column("actor_agent_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_workspace_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_entries_entity_timeline",
        "audit_entries",
        ["entity_kind", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_audit_entries_org_created", "audit_entries", ["org_id", "created_at"], unique=False)
    op.create_index(op.f("ix_audit_entries_org_id"), "audit_entries", ["org_id"], unique=False)

    op.create_table(
        "claude_code_repos",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("repo_external_id", sa.String(), nullable=False),
        sa.Column("skill_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "repo_external_id", name="uq_claude_code_repos_org_repo"),
    )

    op.create_table(
        "claude_code_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("cli_path", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id"),
    )

    op.create_table(
        "coding_agent_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.String(), nullable=False),
        sa.Column("agent_command_id", sa.UUID(), nullable=False),
        sa.Column("command_kind", sa.String(), nullable=False),
        sa.Column("plugin_id", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("effort", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_coding_agent_runs_org_kind_created",
        "coding_agent_runs",
        ["org_id", "command_kind", "created_at"],
        unique=False,
    )

    # coding_agent_activity: partitioned parent only — child partitions are seeded
    # at boot by maintain_coding_agent_activity_partitions() and daily by the
    # core/coding_agent scheduled task.  Alembic autogenerate mis-emits this as a
    # plain op.create_table (it does not understand PARTITION BY RANGE), so we use
    # raw DDL here instead.
    op.execute(  # nosemgrep: python.sqlalchemy.security.audit.avoid-sqlalchemy-text.avoid-sqlalchemy-text
        text(
            "CREATE TABLE IF NOT EXISTS coding_agent_activity ("
            "  run_id UUID NOT NULL,"
            "  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),"
            "  org_id UUID NOT NULL,"
            "  payload JSONB NOT NULL,"
            "  CONSTRAINT coding_agent_activity_pkey PRIMARY KEY (run_id, created_at),"
            "  CONSTRAINT coding_agent_activity_run_id_fkey"
            "    FOREIGN KEY (run_id) REFERENCES coding_agent_runs(id) ON DELETE CASCADE"
            ") PARTITION BY RANGE (created_at)"
        )
    )

    op.create_table(
        "github_app_installations",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("install_external_id", sa.String(), nullable=False),
        sa.Column("account_login", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("install_external_id"),
    )
    op.create_index(
        op.f("ix_github_app_installations_org_id"), "github_app_installations", ["org_id"], unique=False
    )

    op.create_table(
        "github_webhook_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_event_id"),
    )
    op.create_index(
        op.f("ix_github_webhook_events_org_id"), "github_webhook_events", ["org_id"], unique=False
    )

    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("plugin_id", sa.String(), server_default="github", nullable=False),
        sa.Column("repo_external_id", sa.String(), server_default="", nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("source_pr_url", sa.String(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_org_id"), "lessons", ["org_id"], unique=False)
    op.create_index("lessons_repo_idx", "lessons", ["org_id", "plugin_id", "repo_external_id"], unique=False)

    op.create_table(
        "outbox_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", "created_at"),
    )

    op.create_table(
        "pending_human_decisions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("question_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolution_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pending_human_decisions_workflow_resolved",
        "pending_human_decisions",
        ["workflow_execution_id", "resolved_at"],
        unique=False,
    )

    op.create_table(
        "scheduled_runs",
        sa.Column("schedule_id", sa.String(), nullable=False),
        sa.Column("fire_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("schedule_id", "fire_time"),
    )

    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("plugin_id", sa.String(), server_default="github", nullable=False),
        sa.Column("repo_external_id", sa.String(), server_default="", nullable=False),
        sa.Column("pr_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(), server_default="pr_review", nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("current_workflow_execution_id", sa.UUID(), nullable=True),
        sa.Column("findings_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_severity", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("org_id", "source", "source_external_id", name="uq_tickets_org_source_external"),
    )
    op.create_index(op.f("ix_tickets_org_id"), "tickets", ["org_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("github_username", sa.String(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "workflow_executions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("workflow_name", sa.String(), nullable=False),
        sa.Column("workflow_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("current_step_id", sa.String(), nullable=True),
        sa.Column("pending_agent_command_id", sa.UUID(), nullable=True),
        sa.Column("step_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("otel_trace_context", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_executions_pending_agent_command_id",
        "workflow_executions",
        ["pending_agent_command_id"],
        unique=False,
    )
    op.create_index("ix_workflow_executions_state", "workflow_executions", ["state"], unique=False)
    op.create_index("ix_workflow_executions_ticket_id", "workflow_executions", ["ticket_id"], unique=False)

    op.create_table(
        "workspace_agents",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("iam_arn", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("os", sa.String(), nullable=True),
        sa.Column("cpu_count", sa.BigInteger(), nullable=True),
        sa.Column("memory_bytes", sa.BigInteger(), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_shutdown_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_workspace_count", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "instance_id", name="uq_workspace_agents_org_instance"),
    )
    op.create_index(
        "ix_workspace_agents_org_heartbeat", "workspace_agents", ["org_id", "last_heartbeat_at"], unique=False
    )

    # Tables with FK dependencies.
    op.create_table(
        "oauth_identities",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("external_subject", sa.String(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_subject", name="uq_oauth_identity_provider_subject"),
    )
    op.create_index(op.f("ix_oauth_identities_user_id"), "oauth_identities", ["user_id"], unique=False)

    op.create_table(
        "orgs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_timeout_override", sa.Integer(), nullable=True),
        sa.Column("vcs_plugin_id", sa.String(), nullable=True),
        sa.Column("vcs_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("registered_iam_arn", sa.String(), nullable=True),
        sa.Column("aws_region", sa.String(), nullable=True),
        sa.Column("sso_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sso_exempt_owner_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sso_exempt_owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )

    op.create_table(
        "pull_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("plugin_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("repo_external_id", sa.String(), server_default="", nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("author_login", sa.String(), nullable=False),
        sa.Column("author_type", sa.String(), nullable=False),
        sa.Column("base_branch", sa.String(), nullable=False),
        sa.Column("head_branch", sa.String(), nullable=False),
        sa.Column("base_sha", sa.String(), nullable=False),
        sa.Column("head_sha", sa.String(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("is_fork", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("html_url", sa.String(), nullable=False),
        sa.Column(
            "last_synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_id", "external_id", name="uq_pull_requests_plugin_ext"),
    )
    op.create_index(op.f("ix_pull_requests_org_id"), "pull_requests", ["org_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("sso_satisfied_for_org_id", sa.UUID(), nullable=True),
        sa.Column("sso_satisfied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("csrf_token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)

    op.create_table(
        "user_emails",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_emails_email_lower", "user_emails", [sa.literal_column("lower(email)")], unique=False
    )
    op.create_index(op.f("ix_user_emails_user_id"), "user_emails", ["user_id"], unique=False)

    op.create_table(
        "user_totp_secrets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("encrypted_secret", sa.LargeBinary(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )

    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("owning_agent_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_command_id", sa.UUID(), nullable=True),
        sa.Column("max_idle_seconds", sa.Integer(), server_default="600", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("destroyed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("destroy_attempts", sa.Integer(), nullable=False),
        sa.Column("last_destroy_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_destroy_error", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["owning_agent_id"], ["workspace_agents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workspaces_org_created", "workspaces", ["org_id", "created_at"], unique=False)
    op.create_index(op.f("ix_workspaces_org_id"), "workspaces", ["org_id"], unique=False)
    op.create_index("ix_workspaces_owning_agent_id", "workspaces", ["owning_agent_id"], unique=False)
    op.create_index("ix_workspaces_status_expires", "workspaces", ["status", "expires_at"], unique=False)

    op.create_table(
        "bearer_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_ip", postgresql.INET(), nullable=True),
        sa.Column("issued_iam_arn", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["workspace_agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_bearer_tokens_issued_iam_arn", "bearer_tokens", ["issued_iam_arn"], unique=False)
    op.create_index("ix_bearer_tokens_org_issued", "bearer_tokens", ["org_id", "issued_at"], unique=False)

    op.create_table(
        "byok_keys",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("encrypted_value", sa.Text(), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "provider"),
    )

    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invited_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_invitations_email_lower", "invitations", [sa.literal_column("lower(email)")], unique=False
    )
    op.create_index(op.f("ix_invitations_org_id"), "invitations", ["org_id"], unique=False)

    op.create_table(
        "mcp_credentials",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("encrypted_access_token", sa.Text(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("allowed_tools", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("upstream_identity", sa.String(), nullable=True),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_refresh_status", sa.String(length=8), nullable=True),
        sa.Column("last_refresh_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "provider"),
    )

    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("handle", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "org_id"),
        sa.UniqueConstraint("org_id", "handle", name="uq_membership_org_handle"),
    )
    op.create_index("ix_memberships_org_role", "memberships", ["org_id", "role"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "notifications_dedup_subject_idx",
        "notifications",
        ["user_id", "type", "subject_type", "subject_id"],
        unique=False,
        postgresql_where="subject_type IS NOT NULL",
    )
    op.create_index(
        "notifications_user_org_type_idx",
        "notifications",
        ["user_id", "org_id", "type", "created_at"],
        unique=False,
    )
    op.create_index(
        "notifications_user_read_created_idx",
        "notifications",
        ["user_id", "read_at", "created_at"],
        unique=False,
    )

    op.create_table(
        "org_coding_agents",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("plugin_id", sa.String(length=64), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "plugin_id"),
    )

    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("pr_id", sa.UUID(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("trigger_reason", sa.String(), server_default="pr_ready", nullable=False),
        sa.Column("destination", sa.String(), server_default="vcs", nullable=False),
        sa.Column("scope_kind", sa.String(), server_default="full", nullable=False),
        sa.Column("commit_sha_at_start", sa.String(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["pr_id"], ["pull_requests.id"]),
        sa.ForeignKeyConstraint(["run_id"], ["coding_agent_runs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pr_id", "sequence_number", name="uq_reviews_pr_sequence"),
    )
    op.create_index(op.f("ix_reviews_org_id"), "reviews", ["org_id"], unique=False)
    op.create_index("ix_reviews_pr_sequence", "reviews", ["pr_id", "sequence_number"], unique=False)
    op.create_index(
        "ix_reviews_pr_status_created", "reviews", ["pr_id", "status", "created_at"], unique=False
    )

    op.create_table(
        "sso_configs",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("idp_metadata_xml", sa.Text(), nullable=False),
        sa.Column("jit_enabled", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("email_domains", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("exempt_owner_user_id", sa.UUID(), nullable=True),
        sa.Column("sp_private_key_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("sp_certificate", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["exempt_owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id"),
    )

    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("pr_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("finding_display_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("confidence", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("rule_violated", sa.String(), nullable=False),
        sa.Column("rule_source", sa.String(), nullable=False),
        sa.Column("suggested_fix", sa.String(), nullable=False),
        sa.Column("file", sa.String(), nullable=True),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["pr_id"], ["pull_requests.id"]),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pr_id", "finding_display_id", name="uq_findings_pr_display_id"),
    )
    op.create_index("ix_findings_org", "findings", ["org_id"], unique=False)
    op.create_index("ix_findings_pr", "findings", ["pr_id"], unique=False)

    op.create_table(
        "mcp_review_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )

    # Partial indexes + CHECK constraint declared on the corresponding model __table_args__ but not emitted by autogenerate (raw-DDL only via op.execute since postgresql_where + named CheckConstraint don't always round-trip cleanly through autogenerate).
    op.execute(
        text(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_user_emails_email_active "
            "ON user_emails (lower(email)) WHERE verified_at IS NOT NULL"
        )
    )
    op.execute(
        text(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_invitations_pending_org_email "
            "ON invitations (org_id, lower(email)) WHERE accepted_at IS NULL"
        )
    )
    op.execute(
        text(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_orgs_registered_iam_arn "
            "ON orgs (registered_iam_arn) WHERE registered_iam_arn IS NOT NULL"
        )
    )
    op.execute(
        text(
            "ALTER TABLE orgs ADD CONSTRAINT ck_orgs_arn_region_paired "
            "CHECK ((registered_iam_arn IS NULL) = (aws_region IS NULL))"
        )
    )
    op.execute(
        text(
            "CREATE INDEX IF NOT EXISTS ix_bearer_tokens_agent_active "
            "ON bearer_tokens (agent_id, expires_at) WHERE revoked_at IS NULL"
        )
    )


def downgrade() -> None:
    """Baseline is not reversible — there is nothing below it to migrate down to."""
    raise NotImplementedError("baseline is not reversible")
