"""domain/tickets — yaaos's unit of work."""

from app.domain.tickets import web  # noqa: F401
from app.domain.tickets.notifications import build_status_change_specs
from app.domain.tickets.service import (
    InvalidTicketTransition,
    Ticket,
    TicketFilter,
    TicketNotFoundError,
    TicketStatus,
    abandon,
    attach_pr_to_ticket,
    attach_workflow_execution,
    complete,
    create,
    create_for_pr,
    fail,
    get,
    get_by_pr,
    get_payload,
    get_workspace_ticket_context,
    list_running_older_than,
    list_tickets,
    set_workflow_execution,
    update_findings_summary,
    upsert_ticket_for_pr,
)

__all__ = [
    "InvalidTicketTransition",
    "Ticket",
    "TicketFilter",
    "TicketNotFoundError",
    "TicketStatus",
    "abandon",
    "attach_pr_to_ticket",
    "attach_workflow_execution",
    "build_status_change_specs",
    "complete",
    "create",
    "create_for_pr",
    "fail",
    "get",
    "get_by_pr",
    "get_payload",
    "get_workspace_ticket_context",
    "list_running_older_than",
    "list_tickets",
    "set_workflow_execution",
    "update_findings_summary",
    "upsert_ticket_for_pr",
]
