"""domain/tickets — yaaos's unit of work, including the PR mirror."""

from app.domain.tickets import web  # noqa: F401
from app.domain.tickets.notifications import build_status_change_specs
from app.domain.tickets.pull_request import (
    PRState,
    PullRequest,
    PullRequestNotFoundError,
    get_by_external,
    list_by_ids,
    update_state,
    upsert,
)
from app.domain.tickets.pull_request import (
    get as get_pull_request,
)
from app.domain.tickets.service import (
    InvalidTicketTransition,
    Ticket,
    TicketFilter,
    TicketNotFoundError,
    TicketStatus,
    abandon,
    attach_pr_to_ticket,
    complete,
    create_from_pr,
    create_from_schedule,
    fail,
    get,
    get_by_pr,
    get_payload,
    list_running_older_than,
    list_tickets,
    mint_branch_name,
    notify_ticket_status_change,
    set_current_run,
    transition_ticket_on_run_paused,
    transition_ticket_on_run_resumed,
    transition_ticket_on_run_start,
    transition_ticket_on_run_terminal,
    update_findings_summary,
)

__all__ = [
    "InvalidTicketTransition",
    "PRState",
    "PullRequest",
    "PullRequestNotFoundError",
    "Ticket",
    "TicketFilter",
    "TicketNotFoundError",
    "TicketStatus",
    "abandon",
    "attach_pr_to_ticket",
    "build_status_change_specs",
    "complete",
    "create_from_pr",
    "create_from_schedule",
    "fail",
    "get",
    "get_by_external",
    "get_by_pr",
    "get_payload",
    "get_pull_request",
    "list_by_ids",
    "list_running_older_than",
    "list_tickets",
    "mint_branch_name",
    "notify_ticket_status_change",
    "set_current_run",
    "transition_ticket_on_run_paused",
    "transition_ticket_on_run_resumed",
    "transition_ticket_on_run_start",
    "transition_ticket_on_run_terminal",
    "update_findings_summary",
    "update_state",
    "upsert",
]
