"""core/workspace — provisioning + centralized lifecycle."""

# Register the workspace sink into agent_gateway's single-slot registry so
# agent_gateway never imports core/workspace directly. The canonical import
# direction is workspace → agent_gateway (workspace uses the transport and
# registers its sink here).
from app.core.agent_gateway import register_report_sink as _register_report_sink
from app.core.workspace.agent_report import WorkspaceAgentReportSinkImpl
from app.core.workspace.commands import (
    CleanupWorkspace,
    CleanupWorkspaceInputs,
    CleanupWorkspaceOutputs,
    ProvisionWorkspace,
    ProvisionWorkspaceInputs,
    ProvisionWorkspaceOutputs,
    RefreshWorkspaceAuth,
    RefreshWorkspaceAuthInputs,
    RefreshWorkspaceAuthOutputs,
)
from app.core.workspace.commands_base import WorkspaceOpCommand
from app.core.workspace.dispatch import (
    dispatch_via_workspace,
    release_claim,
    try_claim,
)
from app.core.workspace.remote_provider import register_workspace_providers
from app.core.workspace.service import (
    close_workspace,
    get_provider,
    get_workspace_claim_state,
    get_workspace_command_state,
    get_workspace_info,
    get_workspace_owner,
    get_workspace_statuses,
    health_check_all,
    is_workspace_provider_registered,
    list_workspace_providers,
    register_workspace_provider,
    replace_workspace_provider,
    set_workspace_providers_for_tests,
    update_workspace_status,
)
from app.core.workspace.types import (
    CodingAgentCliResult,
    HealthStatus,
    NetworkPolicy,
    OnStreamLine,
    RepoRefForSpec,
    ResourceCaps,
    Workspace,
    WorkspaceClaimFailed,
    WorkspaceClaimState,
    WorkspaceCommandState,
    WorkspaceDestroyError,
    WorkspaceError,
    WorkspaceExecError,
    WorkspaceExpiredError,
    WorkspaceInfo,
    WorkspaceNotFoundError,
    WorkspaceOwner,
    WorkspaceProvider,
    WorkspaceProvisionError,
    WorkspaceSpec,
    WorkspaceStatus,
)

_register_report_sink(WorkspaceAgentReportSinkImpl())

__all__ = [
    "CleanupWorkspace",
    "CleanupWorkspaceInputs",
    "CleanupWorkspaceOutputs",
    "CodingAgentCliResult",
    "HealthStatus",
    "NetworkPolicy",
    "OnStreamLine",
    "ProvisionWorkspace",
    "ProvisionWorkspaceInputs",
    "ProvisionWorkspaceOutputs",
    "RefreshWorkspaceAuth",
    "RefreshWorkspaceAuthInputs",
    "RefreshWorkspaceAuthOutputs",
    "RepoRefForSpec",
    "ResourceCaps",
    "Workspace",
    "WorkspaceAgentReportSinkImpl",
    "WorkspaceClaimFailed",
    "WorkspaceClaimState",
    "WorkspaceCommandState",
    "WorkspaceDestroyError",
    "WorkspaceError",
    "WorkspaceExecError",
    "WorkspaceExpiredError",
    "WorkspaceInfo",
    "WorkspaceNotFoundError",
    "WorkspaceOpCommand",
    "WorkspaceOwner",
    "WorkspaceProvider",
    "WorkspaceProvisionError",
    "WorkspaceSpec",
    "WorkspaceStatus",
    "close_workspace",
    "dispatch_via_workspace",
    "get_provider",
    "get_workspace_claim_state",
    "get_workspace_command_state",
    "get_workspace_info",
    "get_workspace_owner",
    "get_workspace_statuses",
    "health_check_all",
    "is_workspace_provider_registered",
    "list_workspace_providers",
    "register_workspace_provider",
    "register_workspace_providers",
    "release_claim",
    "replace_workspace_provider",
    "set_workspace_providers_for_tests",
    "try_claim",
    "update_workspace_status",
]
