"""core/workflow — Workflow engine.

See `apps/backend/docs/core_workflow.md`.
"""

from app.core.workflow.models import PendingHumanDecisionRow, WorkflowExecutionRow
from app.core.workflow.service import (
    HANDLE_AGENT_EVENT,
    ROUTE_WORKFLOW,
    START_STEP,
    HitlHistoryEntry,
    WorkflowEngine,
    WorkflowExecutionSummary,
    get_awaiting_human_execution,
    get_engine,
    get_execution_summary,
    handle_agent_event,
    list_active_execution_ids,
    list_all_execution_states,
    list_executions_for_ticket,
    list_hitl_history,
    register_workflow,
    request_cancel,
    resume_hitl,
    route_workflow,
    scoped_engine,
    scoped_workflow,
    start_step,
    unregister_workflow,
)
from app.core.workflow.types import (
    TERMINAL_STATES,
    CommandCategory,
    CommandContext,
    CommandNotRegisteredError,
    Outcome,
    OutcomeKind,
    RetryPolicy,
    Step,
    TerminalAction,
    Workflow,
    WorkflowCommand,
    WorkflowError,
    WorkflowExecutionNotFoundError,
    WorkflowNotFoundError,
    WorkflowState,
)

__all__ = [
    "HANDLE_AGENT_EVENT",
    "ROUTE_WORKFLOW",
    "START_STEP",
    "TERMINAL_STATES",
    "CommandCategory",
    "CommandContext",
    "CommandNotRegisteredError",
    "HitlHistoryEntry",
    "Outcome",
    "OutcomeKind",
    "PendingHumanDecisionRow",
    "RetryPolicy",
    "Step",
    "TerminalAction",
    "Workflow",
    "WorkflowCommand",
    "WorkflowEngine",
    "WorkflowError",
    "WorkflowExecutionNotFoundError",
    "WorkflowExecutionRow",
    "WorkflowExecutionSummary",
    "WorkflowNotFoundError",
    "WorkflowState",
    "get_awaiting_human_execution",
    "get_engine",
    "get_execution_summary",
    "handle_agent_event",
    "list_active_execution_ids",
    "list_all_execution_states",
    "list_executions_for_ticket",
    "list_hitl_history",
    "register_workflow",
    "request_cancel",
    "resume_hitl",
    "route_workflow",
    "scoped_engine",
    "scoped_workflow",
    "start_step",
    "unregister_workflow",
]
