"""domain/integrations — per-(org, provider) hosted-MCP OAuth credentials."""

from app.domain.integrations.service import (
    McpCredential,
    McpCredentialSecret,
    clear,
    connect_callback,
    create_credential,
    get,
    get_secret,
    list_broken_credentials_for_org,
    mark_last_used,
    update_allowlist,
    validate,
)
from app.domain.integrations.types import (
    BrokenCredentialsError,
    IntegrationError,
    IntegrationNotConnectedError,
    IntegrationProvider,
    ProviderConfig,
    ProviderNotRegisteredError,
    get_provider,
    known_providers,
    register_provider,
    set_providers_for_tests,
)

__all__ = [
    "BrokenCredentialsError",
    "IntegrationError",
    "IntegrationNotConnectedError",
    "IntegrationProvider",
    "McpCredential",
    "McpCredentialSecret",
    "ProviderConfig",
    "ProviderNotRegisteredError",
    "clear",
    "connect_callback",
    "create_credential",
    "get",
    "get_provider",
    "get_secret",
    "known_providers",
    "list_broken_credentials_for_org",
    "mark_last_used",
    "register_provider",
    "set_providers_for_tests",
    "update_allowlist",
    "validate",
]
