// Package supervisor implements the long-poll worker loop, identity
// exchange, command routing, heartbeat, and disk-janitor responsibilities
// of the agent's `supervisor` subcommand.
//
// Phase 6 ships the skeleton:
//   - identity exchange against the backend's placeholder verifier
//   - N concurrent claim-loop workers (`Config.Concurrency`)
//   - heartbeat loop reporting an in-memory workspace inventory
//   - command-routing stub that emits a `completed_success` event for any
//     command kind (real workspace spawning + Claude Code invocation
//     lands in a follow-on iteration)
//   - graceful Stop via context cancellation
//
// Real responsibilities deferred to follow-on iterations:
//   - per-workspace OS-process spawning + IPC + cleanup
//   - disk janitor scanning /var/agent/workspaces/
//   - wall-clock timeout enforcement per AgentCommand
//   - OTel SDK + traceparent extraction → child spans
//   - startup reconciliation that surfaces orphans in the first heartbeat
package supervisor

import (
	"context"
	"fmt"
	"os"
	"sync"
	"time"

	"go.opentelemetry.io/otel/attribute"

	"github.com/yaaos/agent/internal/protocol"
	"github.com/yaaos/agent/internal/tracing"
)

// Config carries the supervisor's runtime knobs.
type Config struct {
	BaseURL           string        // backend root, e.g. "https://yaaos.example.com"
	AgentPodID        string        // generated by the pod at startup, persisted locally
	Version           string        // agent binary version (semver)
	SignedSTSRequest  string        // SigV4-signed STS payload (Phase 7); any non-empty string passes the placeholder verifier
	Concurrency       int           // claim-loop workers; defaults to 4
	HeartbeatInterval time.Duration // defaults to 30s
	ClaimWaitSeconds  int           // long-poll horizon per claim; defaults to 30

	// Spawn creates a workspace runner. Defaults to `ExecSpawn(os.Args[0], 5s, log)`
	// — fork+exec of the agent binary's `workspace` subcommand. Tests
	// inject `InProcessSpawn(handler)` so they don't need an OS process.
	Spawn SpawnFunc
}

// Logger is the minimal logging surface the supervisor needs. Real
// integrations plug structlog-like loggers in via this interface; tests
// pass a no-op.
type Logger interface {
	Info(msg string, kv ...any)
	Warn(msg string, kv ...any)
	Error(msg string, kv ...any)
}

type nullLogger struct{}

func (nullLogger) Info(string, ...any)  {}
func (nullLogger) Warn(string, ...any)  {}
func (nullLogger) Error(string, ...any) {}

// Supervisor wires the protocol client into the claim/heartbeat loops.
// Construct with New, then Run blocks until ctx is cancelled.
type Supervisor struct {
	cfg     Config
	client  *protocol.Client
	log     Logger
	agentID string
	pool    *Pool

	// In-memory workspace inventory the heartbeat reports. Each entry
	// tracks the workspace_id, the currently in-flight command_id (if any),
	// and a `running` / `exited` status. The pool's spawn/close path keeps
	// this in lock-step with the live runner set.
	mu        sync.Mutex
	inventory map[string]protocol.HeartbeatWorkspaceEntry
}

// New constructs a Supervisor. The client is wired but identity hasn't
// been exchanged yet — call Run.
func New(cfg Config, client *protocol.Client, log Logger) *Supervisor {
	if log == nil {
		log = nullLogger{}
	}
	if cfg.Concurrency <= 0 {
		cfg.Concurrency = 4
	}
	if cfg.HeartbeatInterval <= 0 {
		cfg.HeartbeatInterval = 30 * time.Second
	}
	if cfg.ClaimWaitSeconds <= 0 {
		cfg.ClaimWaitSeconds = 30
	}
	if cfg.Spawn == nil {
		cfg.Spawn = ExecSpawn(os.Args[0], 5*time.Second, log)
	}
	return &Supervisor{
		cfg:       cfg,
		client:    client,
		log:       log,
		inventory: make(map[string]protocol.HeartbeatWorkspaceEntry),
		pool:      NewPool(cfg.Spawn, log),
	}
}

// Run exchanges identity and starts the claim + heartbeat goroutines.
// Blocks until ctx is cancelled or identity exchange fails fatally.
func (s *Supervisor) Run(ctx context.Context) error {
	resp, err := s.exchangeIdentity(ctx)
	if err != nil {
		return fmt.Errorf("identity exchange: %w", err)
	}
	s.agentID = resp.AgentID
	s.client.SetBearer(resp.Bearer)
	s.log.Info("supervisor.identity_exchanged", "agent_id", s.agentID)

	var wg sync.WaitGroup
	for i := 0; i < s.cfg.Concurrency; i++ {
		wg.Add(1)
		go func(workerNum int) {
			defer wg.Done()
			s.claimLoop(ctx, workerNum)
		}(i)
	}
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.heartbeatLoop(ctx)
	}()
	wg.Wait()
	// Reap any still-running workspace subprocesses on shutdown. Each
	// runner gets SIGTERM → grace → SIGKILL via its own Close.
	s.pool.CloseAll(context.Background())
	return nil
}

func (s *Supervisor) exchangeIdentity(ctx context.Context) (*protocol.IdentityExchangeResponse, error) {
	return s.client.ExchangeIdentity(ctx, protocol.IdentityExchangeRequest{
		AgentPodID:    s.cfg.AgentPodID,
		Version:       s.cfg.Version,
		SignedRequest: s.cfg.SignedSTSRequest,
	})
}

// claimLoop runs one long-poll worker. On a successful claim it dispatches
// the command via routeCommand and emits the terminal event. On ErrNoCommand
// (204) it re-arms; on ctx cancellation it exits.
func (s *Supervisor) claimLoop(ctx context.Context, workerNum int) {
	for {
		if ctx.Err() != nil {
			return
		}
		cmd, err := s.client.ClaimCommand(ctx, s.agentID, protocol.ClaimRequest{
			WaitSeconds: s.cfg.ClaimWaitSeconds,
		})
		if err != nil {
			if err == protocol.ErrNoCommand {
				continue
			}
			if ctx.Err() != nil {
				return
			}
			s.log.Warn("supervisor.claim_error", "worker", workerNum, "err", err.Error())
			// Backoff before retrying so a broken backend doesn't tight-loop.
			select {
			case <-ctx.Done():
				return
			case <-time.After(2 * time.Second):
			}
			continue
		}
		s.routeCommand(ctx, cmd)
	}
}

// heartbeatLoop reports liveness + workspace inventory on the configured
// interval. The reconciliation response (`forgotten_workspaces`) is logged;
// applying it to real OS processes lands in the follow-on iteration.
func (s *Supervisor) heartbeatLoop(ctx context.Context) {
	ticker := time.NewTicker(s.cfg.HeartbeatInterval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			s.sendHeartbeat(ctx)
		}
	}
}

func (s *Supervisor) sendHeartbeat(ctx context.Context) {
	resp, err := s.client.Heartbeat(ctx, s.agentID, protocol.HeartbeatRequest{
		ReportedAt: time.Now().UTC(),
		Workspaces: s.snapshotInventory(),
	})
	if err != nil {
		s.log.Warn("supervisor.heartbeat_error", "err", err.Error())
		return
	}
	if len(resp.ForgottenWorkspaces) > 0 {
		s.log.Info("supervisor.heartbeat_reconciled",
			"forgotten_count", len(resp.ForgottenWorkspaces))
	}
}

// routeCommand dispatches an AgentCommand into the per-workspace pool +
// forwards the resulting event back to the control plane. The pool spawns
// a workspace subprocess on the first command for a given workspace_id,
// reuses it for subsequent commands, and reaps it after CleanupWorkspace.
//
// Trace propagation: the command header carries the backend's W3C
// traceparent; we extract that into the ctx, start a child
// `supervisor.dispatch.<kind>` span, then rewrite the command's
// traceparent on the wire so the workspace subprocess sees our span as
// its parent. The resulting AgentEvent's traceparent likewise carries
// our span back to the backend.
//
// On runner I/O error / context cancel, the pool emits a synthetic
// `completed_failure` event so the workflow-engine on the backend always
// sees an outcome (it never silently hangs waiting for our reply).
func (s *Supervisor) routeCommand(ctx context.Context, cmd *protocol.AgentCommand) {
	header := cmd.Header()
	s.recordInventory(header.WorkspaceID, header.CommandID, "running")
	defer s.clearInventory(header.WorkspaceID)

	ctx = tracing.ExtractContext(ctx, header.Traceparent)
	ctx, end := tracing.StartSpan(ctx, "supervisor.dispatch."+string(cmd.Kind),
		attribute.String("workspace_id", header.WorkspaceID),
		attribute.String("command_id", header.CommandID),
		attribute.String("kind", string(cmd.Kind)),
	)

	// Rewrite the wire's traceparent so the workspace subprocess + the
	// AgentEvent we'll post back upstream both see this dispatch span as
	// their parent. The original (backend) parent is recorded via the
	// SDK's span linkage — no information lost.
	childTP := tracing.InjectTraceparent(ctx)
	if childTP != "" {
		setHeaderTraceparent(cmd, childTP)
	}

	event := s.pool.Dispatch(ctx, cmd)
	// The pool's failureEvent / runner-relayed events keep whatever
	// traceparent the dispatcher saw. Make sure the supervisor's span is
	// what the backend correlates against.
	if childTP != "" {
		event.Traceparent = childTP
	}

	var postErr error
	if err := s.client.PostCommandEvent(ctx, header.CommandID, event); err != nil {
		if err == protocol.ErrStaleClaim {
			s.log.Info("supervisor.event_stale_claim", "command_id", header.CommandID)
		} else {
			postErr = err
			s.log.Warn("supervisor.event_post_failed", "command_id", header.CommandID, "err", err.Error())
		}
	}
	// Span carries the dispatch-level error (post-back failure or pool
	// failure if Dispatch returned a completed_failure event).
	if event.Kind == protocol.EventCompletedFailure {
		end(fmt.Errorf("dispatch failure: %s", event.FailureReason))
		return
	}
	end(postErr)
}

// setHeaderTraceparent mutates the concrete AgentCommand payload's
// embedded CommandHeader.Traceparent in place. Used to rewrite the wire's
// trace context to the supervisor's child span before forwarding to the
// workspace subprocess.
func setHeaderTraceparent(cmd *protocol.AgentCommand, tp string) {
	switch cmd.Kind {
	case protocol.KindCreateWorkspace:
		cmd.CreateWorkspace.Traceparent = tp
	case protocol.KindWriteFiles:
		cmd.WriteFiles.Traceparent = tp
	case protocol.KindRefreshWorkspaceAuth:
		cmd.RefreshWorkspaceAuth.Traceparent = tp
	case protocol.KindInvokeClaudeCode:
		cmd.InvokeClaudeCode.Traceparent = tp
	case protocol.KindCleanupWorkspace:
		cmd.CleanupWorkspace.Traceparent = tp
	}
}

func (s *Supervisor) recordInventory(workspaceID, commandID, status string) {
	if workspaceID == "" {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.inventory[workspaceID] = protocol.HeartbeatWorkspaceEntry{
		WorkspaceID:      workspaceID,
		Status:           status,
		CurrentCommandID: commandID,
	}
}

func (s *Supervisor) clearInventory(workspaceID string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.inventory, workspaceID)
}

func (s *Supervisor) snapshotInventory() []protocol.HeartbeatWorkspaceEntry {
	s.mu.Lock()
	defer s.mu.Unlock()
	out := make([]protocol.HeartbeatWorkspaceEntry, 0, len(s.inventory))
	for _, v := range s.inventory {
		out = append(out, v)
	}
	return out
}
