// Package supervisor implements the long-poll worker loop, identity
// exchange, command routing, heartbeat, and disk-janitor responsibilities
// of the agent's `supervisor` subcommand.
//
// Responsibilities:
//   - identity exchange against the backend's placeholder verifier
//   - N concurrent claim-loop workers (`Config.Concurrency`)
//   - heartbeat loop reporting an in-memory workspace inventory
//   - command routing that dispatches each AgentCommand kind
//   - graceful Stop via context cancellation
package supervisor

import (
	"context"
	"fmt"
	"os"
	"sync"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"github.com/yaaos/agent/internal/activity"
	"github.com/yaaos/agent/internal/backoff"
	"github.com/yaaos/agent/internal/observability"
	"github.com/yaaos/agent/internal/protocol"
	"github.com/yaaos/agent/internal/tracing"
)

// connection surface tags for the connection.failures / connection.backoff_seconds
// metric attributes. Centralized here so call sites can't typo a label.
const (
	surfaceSTS       = "sts"
	surfaceClaim     = "claim"
	surfaceHeartbeat = "heartbeat"
	surfaceWS        = "ws"
)

// classifyConnErr returns "auth" if the error carries a 401 or 403
// status indication, "network" otherwise. The protocol client wraps
// HTTP failures as `fmt.Errorf("%s %s: %d %s", method, path, status, body)`
// so a substring check on the status segment is sufficient for the
// metric attribute. Same ramp applies either way — the label is for
// dashboarding, not for cadence selection.
func classifyConnErr(err error) string {
	if err == nil {
		return ""
	}
	s := err.Error()
	if containsStatus(s, "401") || containsStatus(s, "403") {
		return "auth"
	}
	return "network"
}

func containsStatus(s, code string) bool {
	// Look for `: <code> ` to match the doJSON formatting and avoid
	// matching a substring of a port / latency / unrelated number.
	needle := ": " + code + " "
	for i := 0; i+len(needle) <= len(s); i++ {
		if s[i:i+len(needle)] == needle {
			return true
		}
	}
	return false
}

// recordBackoff bumps the connection.failures counter and sets the
// connection.backoff_seconds gauge to the schedule's next delay BEFORE
// calling Sleep. Centralizes the boilerplate so each retry site stays
// readable.
func recordBackoff(ctx context.Context, sched *backoff.Schedule, surface string, err error) {
	class := classifyConnErr(err)
	observability.Metrics().ConnectionFailures.Add(ctx, 1,
		metric.WithAttributes(
			attribute.String("surface", surface),
			attribute.String("class", class),
		),
	)
	observability.Metrics().ConnectionBackoffSeconds.Record(ctx, sched.Peek().Seconds(),
		metric.WithAttributes(attribute.String("surface", surface)),
	)
}

// Config carries the supervisor's runtime knobs.
type Config struct {
	BaseURL           string        // backend root, e.g. "https://yaaos.example.com"
	AgentPodID        string        // generated by the pod at startup, persisted locally
	Version           string        // agent binary version (semver)
	SignedSTSRequest  string        // SigV4-signed STS payload; any non-empty string passes the placeholder verifier
	Concurrency       int           // claim-loop workers; defaults to 4
	HeartbeatInterval time.Duration // defaults to 30s
	ClaimWaitSeconds  int           // long-poll horizon per claim; defaults to 30

	// Spawn creates a workspace runner. Defaults to `ExecSpawn(os.Args[0], 5s, log)`
	// — fork+exec of the agent binary's `workspace` subcommand. Tests
	// inject `InProcessSpawn(handler)` so they don't need an OS process.
	Spawn SpawnFunc

	// WorkspaceRoot is the parent directory the workspace process clones
	// repos into. On startup the supervisor scans this for orphan
	// workspaces from a previous run and reports them as
	// `status="unknown"` in the first heartbeat. Empty disables
	// reconciliation; production usually sets it from
	// `YAAOS_WORKSPACE_ROOT`.
	WorkspaceRoot string

	// ActivityWSURL is the backend's activity-stream WebSocket URL
	// (e.g. "wss://yaaos.example.com/api/v1/agents/<agent_id>/activity").
	// Empty disables the WS path: progress events fall back to per-event
	// HTTP POSTs. Non-empty: the supervisor dials at startup,
	// constructs an `activity.Conductor`, and routes progress events
	// through it. Demand-pull semantics apply — events for workspaces
	// the backend hasn't sent `subscribe` for are dropped at the
	// Conductor's gate. The literal `{agent_id}` placeholder
	// gets substituted post-identity-exchange.
	ActivityWSURL string

	// ActivityBatchInterval controls the Conductor's flush cadence.
	// Defaults to 250ms.
	ActivityBatchInterval time.Duration
}

// Logger is the minimal logging surface the supervisor needs. Real
// integrations plug structlog-like loggers in via this interface; tests
// pass a no-op.
type Logger interface {
	Info(msg string, kv ...any)
	Warn(msg string, kv ...any)
	Error(msg string, kv ...any)
}

type nullLogger struct{}

func (nullLogger) Info(string, ...any)  {}
func (nullLogger) Warn(string, ...any)  {}
func (nullLogger) Error(string, ...any) {}

// Supervisor wires the protocol client into the claim/heartbeat loops.
// Construct with New, then Run blocks until ctx is cancelled.
type Supervisor struct {
	cfg     Config
	client  *protocol.Client
	log     Logger
	agentID string
	pool    *Pool

	// In-memory workspace inventory the heartbeat reports. Each entry
	// tracks the workspace_id, the currently in-flight command_id (if any),
	// and a `running` / `exited` status. The pool's spawn/close path keeps
	// this in lock-step with the live runner set.
	mu        sync.Mutex
	inventory map[string]protocol.HeartbeatWorkspaceEntry

	// workspacePaths maps workspace_id → on-disk path for orphan
	// directories the startup scan found. The disk janitor
	// consults this when the heartbeat response carries a
	// `forgotten_workspaces` list, then `os.RemoveAll`s the named paths.
	// Live workspaces' paths are owned by the workspace process itself
	// (not the supervisor) — only orphans (from a previous run) need
	// supervisor-side path tracking.
	workspacePaths map[string]string

	// conductor + wsConn are non-nil iff cfg.ActivityWSURL is set AND
	// the WS dial succeeded. Progress events route through the
	// Conductor when present; otherwise they fall back to HTTP POSTs.
	// Terminal events always use HTTP — only progress
	// streaming is on the WS.
	conductor *activity.Conductor
	wsConn    *activity.WSConn
	// wsReadLoopDone is closed when the active activity-WS read loop
	// returns. wsReconnectLoop reads from it to decide when to re-dial.
	wsReadLoopDone chan struct{}

	// Per-surface backoff schedules. A misconfigured ARN slowing down
	// STS exchange must not slow heartbeat retries on an unrelated
	// transient blip; each surface owns its own attempt counter.
	stsBackoff       *backoff.Schedule
	claimBackoff     *backoff.Schedule
	heartbeatBackoff *backoff.Schedule
	wsBackoff        *backoff.Schedule
}

// New constructs a Supervisor. The client is wired but identity hasn't
// been exchanged yet — call Run.
func New(cfg Config, client *protocol.Client, log Logger) *Supervisor {
	if log == nil {
		log = nullLogger{}
	}
	if cfg.Concurrency <= 0 {
		cfg.Concurrency = 4
	}
	if cfg.HeartbeatInterval <= 0 {
		cfg.HeartbeatInterval = 30 * time.Second
	}
	if cfg.ClaimWaitSeconds <= 0 {
		cfg.ClaimWaitSeconds = 30
	}
	if cfg.Spawn == nil {
		cfg.Spawn = ExecSpawn(os.Args[0], 5*time.Second, log)
	}
	if cfg.ActivityBatchInterval <= 0 {
		cfg.ActivityBatchInterval = 250 * time.Millisecond
	}
	return &Supervisor{
		cfg:              cfg,
		client:           client,
		log:              log,
		inventory:        make(map[string]protocol.HeartbeatWorkspaceEntry),
		workspacePaths:   make(map[string]string),
		pool:             NewPool(cfg.Spawn, log),
		stsBackoff:       backoff.New(),
		claimBackoff:     backoff.New(),
		heartbeatBackoff: backoff.New(),
		wsBackoff:        backoff.New(),
	}
}

// Run exchanges identity and starts the claim + heartbeat goroutines.
// Blocks until ctx is cancelled or identity exchange fails fatally.
func (s *Supervisor) Run(ctx context.Context) error {
	// STS bootstrap: retry forever on the 1m/3m/5m/15m/60m schedule.
	// A misconfigured ARN (403) doesn't fix itself by us crashing-and-
	// restarting the process; staying alive lets the local log + OTel
	// metrics show the operator what's wrong without a restart loop.
	var resp *protocol.IdentityExchangeResponse
	for {
		var err error
		resp, err = s.exchangeIdentity(ctx)
		if err == nil {
			s.stsBackoff.Reset()
			break
		}
		if ctx.Err() != nil {
			return ctx.Err()
		}
		recordBackoff(ctx, s.stsBackoff, surfaceSTS, err)
		s.log.Warn("supervisor.identity_exchange_failed",
			"err", err.Error(),
			"class", classifyConnErr(err),
			"next_sleep_seconds", int(s.stsBackoff.Peek().Seconds()),
		)
		if sleepErr := s.stsBackoff.Sleep(ctx); sleepErr != nil {
			return sleepErr
		}
	}
	s.agentID = resp.AgentID
	s.client.SetBearer(resp.Bearer)
	s.log.Info("supervisor.identity_exchanged", "agent_id", s.agentID)

	// Startup reconciliation: any workspace directory left over from a
	// previous run gets pre-loaded into the inventory as
	// `status="unknown"` so the first heartbeat reports it. The backend
	// decides whether to reclaim or signal cleanup via
	// `HeartbeatResponse.forgotten_workspaces` — the disk janitor in
	// `sendHeartbeat` applies that.
	orphans, paths := scanOrphanWorkspaces(s.cfg.WorkspaceRoot, s.log)
	if len(orphans) > 0 {
		s.mu.Lock()
		for _, o := range orphans {
			s.inventory[o.WorkspaceID] = o
		}
		for id, p := range paths {
			s.workspacePaths[id] = p
		}
		s.mu.Unlock()
		s.log.Info("supervisor.reconciliation_orphans", "count", len(orphans))
	}

	// Activity WebSocket: opt-in via cfg.ActivityWSURL. On dial failure
	// the supervisor keeps running with progress events on HTTP — the
	// WS is an efficiency hop, not a correctness requirement.
	if s.cfg.ActivityWSURL != "" {
		s.setupActivityWS(ctx, resp.Bearer)
	}

	var wg sync.WaitGroup
	for i := 0; i < s.cfg.Concurrency; i++ {
		wg.Add(1)
		go func(workerNum int) {
			defer wg.Done()
			s.claimLoop(ctx, workerNum)
		}(i)
	}
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.heartbeatLoop(ctx)
	}()
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.bearerRefreshLoop(ctx, resp.ExpiresAt)
	}()
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.diskSweepLoop(ctx)
	}()
	wg.Wait()
	// Tear down the activity WS first so the read-loop exits before the
	// pool shuts down; otherwise a slow flush could race with ctx cancel.
	if s.conductor != nil {
		s.conductor.Stop()
	}
	if s.wsConn != nil {
		_ = s.wsConn.Close()
	}
	// Reap any still-running workspace subprocesses on shutdown. Each
	// runner gets SIGTERM → grace → SIGKILL via its own Close.
	s.pool.CloseAll(context.Background())
	return nil
}

// setupActivityWS dials the activity-stream WebSocket and wires the
// Conductor. Dial failure is logged but not fatal — the supervisor
// falls back to HTTP-only progress posts. A read-loop transport error
// triggers a reconnect attempt on the WS backoff schedule (1m/3m/5m/...).
func (s *Supervisor) setupActivityWS(ctx context.Context, bearer string) {
	if s.dialAndStartWS(ctx, bearer) {
		s.wsBackoff.Reset()
	}
	// Reconnect goroutine: if the initial dial failed OR the read-loop
	// later exits, sleep on the WS backoff and re-try. Lives for the
	// life of ctx.
	go s.wsReconnectLoop(ctx, bearer)
}

// dialAndStartWS performs one dial attempt + wires the Conductor + spawns
// the read-loop. Returns true on success. Read-loop exit signals
// `s.wsReadLoopDone` (a channel created per-attempt) so the reconnect
// loop can detect it.
func (s *Supervisor) dialAndStartWS(ctx context.Context, bearer string) bool {
	dialCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	url := s.cfg.ActivityWSURL
	conn, err := activity.Dial(dialCtx, url, bearer)
	if err != nil {
		recordBackoff(ctx, s.wsBackoff, surfaceWS, err)
		s.log.Warn("supervisor.activity_ws_dial_failed",
			"url", url,
			"err", err.Error(),
			"class", classifyConnErr(err),
			"next_sleep_seconds", int(s.wsBackoff.Peek().Seconds()),
		)
		return false
	}
	s.wsConn = conn
	s.conductor = activity.NewConductor(s.cfg.ActivityBatchInterval, conn.Send)
	s.conductor.Start(ctx)
	s.wsReadLoopDone = make(chan struct{})
	// Read-loop: ctx cancel unblocks Read. RunInbound returns on the
	// first transport error; we log and let the reconnect loop re-dial.
	go func() {
		defer close(s.wsReadLoopDone)
		if err := activity.RunInbound(ctx, conn, s.conductor); err != nil && ctx.Err() == nil {
			s.log.Warn("supervisor.activity_ws_read_loop_exited", "err", err.Error())
		}
	}()
	s.log.Info("supervisor.activity_ws_connected", "url", url)
	return true
}

// wsReconnectLoop waits for the active read-loop to exit, then re-dials
// the activity WS on the WS backoff schedule. Runs for the life of ctx.
// First call here may also handle the case where the initial dial in
// setupActivityWS failed — wsReadLoopDone is nil then, so we go straight
// to the backoff Sleep + re-dial.
func (s *Supervisor) wsReconnectLoop(ctx context.Context, bearer string) {
	for {
		if s.wsReadLoopDone != nil {
			select {
			case <-ctx.Done():
				return
			case <-s.wsReadLoopDone:
			}
		}
		if ctx.Err() != nil {
			return
		}
		// Sleep before re-dialing. Reset is called inside dialAndStartWS
		// (via the caller in setupActivityWS) on success; here we're
		// post-failure so the schedule advances.
		if err := s.wsBackoff.Sleep(ctx); err != nil {
			return
		}
		if s.dialAndStartWS(ctx, bearer) {
			s.wsBackoff.Reset()
		}
	}
}

func (s *Supervisor) exchangeIdentity(ctx context.Context) (*protocol.IdentityExchangeResponse, error) {
	return s.client.ExchangeIdentity(ctx, protocol.IdentityExchangeRequest{
		AgentPodID:    s.cfg.AgentPodID,
		Version:       s.cfg.Version,
		SignedRequest: s.cfg.SignedSTSRequest,
	})
}

// bearerRefreshLoop re-exchanges identity ~1 hour before the bearer
// expires so the supervisor keeps running across the 24-hour bearer TTL.
// On exchange failure it logs and retries every 60s — the existing
// bearer remains valid until its own expiry.
func (s *Supervisor) bearerRefreshLoop(ctx context.Context, expiresAt time.Time) {
	const refreshLead = time.Hour
	const retryInterval = 60 * time.Second
	for {
		wait := time.Until(expiresAt.Add(-refreshLead))
		if wait < 0 {
			wait = retryInterval
		}
		select {
		case <-ctx.Done():
			return
		case <-time.After(wait):
		}
		resp, err := s.exchangeIdentity(ctx)
		if err != nil {
			s.log.Warn("supervisor.bearer_refresh_failed", "err", err.Error())
			expiresAt = time.Now().Add(retryInterval)
			continue
		}
		s.client.SetBearer(resp.Bearer)
		expiresAt = resp.ExpiresAt
		s.log.Info("supervisor.bearer_refreshed", "expires_at", expiresAt.Format(time.RFC3339))
	}
}

// diskSweepLoop is the proactive failsafe-5 pass — every 5 minutes it
// walks the workspace root and `RemoveAll`s any directory that's not in
// the supervisor's in-memory pool. Defence against orphans the backend's
// `forgotten_workspaces` response never tells us about (e.g. agent
// crashed mid-create before reporting).
func (s *Supervisor) diskSweepLoop(ctx context.Context) {
	const interval = 5 * time.Minute
	if s.cfg.WorkspaceRoot == "" {
		return
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
		}
		removed := sweepOrphanWorkspaceDirs(s.cfg.WorkspaceRoot, s.knownWorkspaceIDs(), s.log)
		if removed > 0 {
			s.log.Info("supervisor.disk_sweep_removed", "count", removed)
		}
	}
}

// knownWorkspaceIDs returns a snapshot of workspace IDs currently in the
// supervisor's pool — disk-sweep treats anything on disk and NOT in this
// set as an orphan eligible for removal.
func (s *Supervisor) knownWorkspaceIDs() map[string]struct{} {
	s.mu.Lock()
	defer s.mu.Unlock()
	out := make(map[string]struct{}, len(s.workspacePaths))
	for id := range s.workspacePaths {
		out[id] = struct{}{}
	}
	return out
}

// claimLoop runs one long-poll worker. On a successful claim it dispatches
// the command via routeCommand and emits the terminal event. On ErrNoCommand
// (204) it re-arms; on ctx cancellation it exits.
func (s *Supervisor) claimLoop(ctx context.Context, workerNum int) {
	for {
		if ctx.Err() != nil {
			return
		}
		cmd, err := s.client.ClaimCommand(ctx, s.agentID, protocol.ClaimRequest{
			WaitSeconds: s.cfg.ClaimWaitSeconds,
		})
		if err != nil {
			if err == protocol.ErrNoCommand {
				s.claimBackoff.Reset()
				continue
			}
			if ctx.Err() != nil {
				return
			}
			recordBackoff(ctx, s.claimBackoff, surfaceClaim, err)
			s.log.Warn("supervisor.claim_error",
				"worker", workerNum,
				"err", err.Error(),
				"class", classifyConnErr(err),
				"next_sleep_seconds", int(s.claimBackoff.Peek().Seconds()),
			)
			if sleepErr := s.claimBackoff.Sleep(ctx); sleepErr != nil {
				return
			}
			continue
		}
		s.claimBackoff.Reset()
		observability.Metrics().CommandsClaimed.Add(ctx, 1)
		s.routeCommand(ctx, cmd)
	}
}

// heartbeatLoop reports liveness + workspace inventory on the configured
// interval. The reconciliation response (`forgotten_workspaces`) drives
// the disk janitor in sendHeartbeat.
func (s *Supervisor) heartbeatLoop(ctx context.Context) {
	ticker := time.NewTicker(s.cfg.HeartbeatInterval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			s.sendHeartbeat(ctx)
		}
	}
}

func (s *Supervisor) sendHeartbeat(ctx context.Context) {
	resp, err := s.client.Heartbeat(ctx, s.agentID, protocol.HeartbeatRequest{
		ReportedAt: time.Now().UTC(),
		Workspaces: s.snapshotInventory(),
	})
	if err != nil {
		recordBackoff(ctx, s.heartbeatBackoff, surfaceHeartbeat, err)
		s.log.Warn("supervisor.heartbeat_error",
			"err", err.Error(),
			"class", classifyConnErr(err),
			"next_sleep_seconds", int(s.heartbeatBackoff.Peek().Seconds()),
		)
		// Sleep absorbs the configured HeartbeatInterval — the ticker
		// will still fire at its cadence, but the next attempt only
		// proceeds after the backoff window elapses.
		_ = s.heartbeatBackoff.Sleep(ctx)
		return
	}
	s.heartbeatBackoff.Reset()
	if len(resp.ForgottenWorkspaces) == 0 {
		return
	}
	s.log.Info("supervisor.heartbeat_reconciled", "forgotten_count", len(resp.ForgottenWorkspaces))

	// Disk janitor: the backend named workspaces it no
	// longer tracks. Walk the supervisor's path map, `os.RemoveAll`
	// each surviving dir, and drop the cleaned ids from both the path
	// map AND the inventory so the next heartbeat doesn't keep
	// reporting them. Live workspaces still in `s.pool` aren't in
	// `workspacePaths` (their on-disk path lives in the workspace
	// process), so the janitor only touches orphan dirs.
	s.mu.Lock()
	s.workspacePaths = cleanupForgottenWorkspaces(s.workspacePaths, resp.ForgottenWorkspaces, s.log)
	for _, id := range resp.ForgottenWorkspaces {
		// `cleanupForgottenWorkspaces` removes the entry when the path
		// is successfully RemoveAll'd. Absence == cleaned == drop the
		// inventory entry so it stops being reported. Presence ==
		// remove failed; leave inventory alone so the next heartbeat
		// signals the backend to retry.
		if _, stillPresent := s.workspacePaths[id]; !stillPresent {
			delete(s.inventory, id)
		}
	}
	s.mu.Unlock()
}

// routeCommand dispatches an AgentCommand into the per-workspace pool +
// forwards the resulting event back to the control plane. The pool spawns
// a workspace subprocess on the first command for a given workspace_id,
// reuses it for subsequent commands, and reaps it after CleanupWorkspace.
//
// Trace propagation: the command header carries the backend's W3C
// traceparent; we extract that into the ctx, start a child
// `supervisor.dispatch.<kind>` span, then rewrite the command's
// traceparent on the wire so the workspace subprocess sees our span as
// its parent. The resulting AgentEvent's traceparent likewise carries
// our span back to the backend.
//
// On runner I/O error / context cancel, the pool emits a synthetic
// `completed_failure` event so the workflow-engine on the backend always
// sees an outcome (it never silently hangs waiting for our reply).
func (s *Supervisor) routeCommand(ctx context.Context, cmd *protocol.AgentCommand) {
	header := cmd.Header()
	s.recordInventory(header.WorkspaceID, header.CommandID, "running")
	defer s.clearInventory(header.WorkspaceID)

	ctx = tracing.ExtractContext(ctx, header.Traceparent)
	ctx, end := tracing.StartSpan(ctx, "supervisor.dispatch."+string(cmd.Kind),
		attribute.String("workspace_id", header.WorkspaceID),
		attribute.String("command_id", header.CommandID),
		attribute.String("kind", string(cmd.Kind)),
	)

	// Rewrite the wire's traceparent so the workspace subprocess + the
	// AgentEvent we'll post back upstream both see this dispatch span as
	// their parent. The original (backend) parent is recorded via the
	// SDK's span linkage — no information lost.
	childTP := tracing.InjectTraceparent(ctx)
	if childTP != "" {
		setHeaderTraceparent(cmd, childTP)
	}

	// Progress-event forwarder: when the activity WS is up, each in-flight
	// progress AgentEvent goes through the Conductor — batched at ~250ms,
	// filtered by the SubscriptionSet (demand-pull: dropped when no UI is
	// watching this workflow). When the WS isn't configured / dial failed,
	// falls back to per-event HTTP POST. Either way, missing progress events
	// aren't a correctness issue — the terminal event still carries
	// the outcome.
	progressForwarder := func(pev protocol.AgentEvent) {
		if s.conductor != nil {
			s.conductor.Publish(header.WorkspaceID, pev)
			return
		}
		if perr := s.client.PostCommandEvent(ctx, header.CommandID, pev); perr != nil {
			s.log.Warn("supervisor.progress_post_failed",
				"command_id", header.CommandID, "err", perr.Error())
		}
	}

	event := s.pool.Dispatch(ctx, cmd, progressForwarder)
	// The pool's failureEvent / runner-relayed events keep whatever
	// traceparent the dispatcher saw. Make sure the supervisor's span is
	// what the backend correlates against.
	if childTP != "" {
		event.Traceparent = childTP
	}

	var postErr error
	if err := s.client.PostCommandEvent(ctx, header.CommandID, event); err != nil {
		if err == protocol.ErrStaleClaim {
			s.log.Info("supervisor.event_stale_claim", "command_id", header.CommandID)
		} else {
			postErr = err
			s.log.Warn("supervisor.event_post_failed", "command_id", header.CommandID, "err", err.Error())
		}
	}
	// Span carries the dispatch-level error (post-back failure or pool
	// failure if Dispatch returned a completed_failure event).
	result := "success"
	if event.Kind == protocol.EventCompletedFailure || postErr != nil {
		result = "failure"
	}
	observability.Metrics().CommandsCompleted.Add(ctx, 1,
		metric.WithAttributes(attribute.String("result", result),
			attribute.String("kind", string(cmd.Kind))),
	)
	if event.Kind == protocol.EventCompletedFailure {
		end(fmt.Errorf("dispatch failure: %s", event.FailureReason))
		return
	}
	end(postErr)
}

// setHeaderTraceparent mutates the concrete AgentCommand payload's
// embedded CommandHeader.Traceparent in place. Used to rewrite the wire's
// trace context to the supervisor's child span before forwarding to the
// workspace subprocess.
func setHeaderTraceparent(cmd *protocol.AgentCommand, tp string) {
	switch cmd.Kind {
	case protocol.KindCreateWorkspace:
		cmd.CreateWorkspace.Traceparent = tp
	case protocol.KindWriteFiles:
		cmd.WriteFiles.Traceparent = tp
	case protocol.KindRefreshWorkspaceAuth:
		cmd.RefreshWorkspaceAuth.Traceparent = tp
	case protocol.KindInvokeClaudeCode:
		cmd.InvokeClaudeCode.Traceparent = tp
	case protocol.KindCleanupWorkspace:
		cmd.CleanupWorkspace.Traceparent = tp
	}
}

func (s *Supervisor) recordInventory(workspaceID, commandID, status string) {
	if workspaceID == "" {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.inventory[workspaceID] = protocol.HeartbeatWorkspaceEntry{
		WorkspaceID:      workspaceID,
		Status:           status,
		CurrentCommandID: commandID,
	}
}

func (s *Supervisor) clearInventory(workspaceID string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.inventory, workspaceID)
}

func (s *Supervisor) snapshotInventory() []protocol.HeartbeatWorkspaceEntry {
	s.mu.Lock()
	defer s.mu.Unlock()
	out := make([]protocol.HeartbeatWorkspaceEntry, 0, len(s.inventory))
	for _, v := range s.inventory {
		out = append(out, v)
	}
	return out
}
